config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :offers do
    collection do
      get 'search'
    end
    resources :questions do
      resources :answers
    end
  end

  root 'offers#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  searchkick
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :state
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :offer
  has_many :answers
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :offers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :offers
  has_many :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :find_question
  before_action :find_answer, only: [:show, :edit, :update, :destroy]


  def create
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to offer_path(@question.offer)
    else
      flash[:error] = "Error ocurred on answering the question"
    end
  end

  def new
    @answer = @question.answers.build
  end

  def show

  end

  def edit

  end

  def update
    if @answer.update(answer_params) && current_user == @question.offer.user
      redirect_to offer_path(@question.offer)
    else
      render 'edit'
    end
  end

  def destroy
    if current_user == @question.offer.user
      @answer.destroy
      redirect_to offer_path(@question.offer)
    else
      flash[:info] = "You can't delete this answer"
    end
  end

  private
  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = @question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:content, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :find_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    if params[:search].present?
      @offers = Offer.search(params[:search])
    else
      @offers = Offer.all
    end
  end

  def index
    if params[:state].blank?
      @offers = Offer.all.order("created_at DESC")
    else
      @state_id = State.find_by(title: params[:state]).id
      @offers = Offer.where(state_id: @state_id).order("created_at DESC")
    end

  end

  def show
  end

  def edit
  end

  def update
    if @offer.update(offer_params)
      redirect_to @offer
    else
      render 'edit'
    end
  end

  def new
    @offer = current_user.offers.build
  end

  def create
    @offer = current_user.offers.build(offer_params)
    if @offer.save
      redirect_to @offer
    else
      render 'new'
    end
  end

  def destroy
    @offer.destroy
    redirect_to root_path
  end

  private
    def find_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:title, :description, :price, :photo, :user_id, :state_id)
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :find_offer
  before_action :find_question, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def create
    @question = @offer.questions.build(question_params)
    @question.user_id = current_user.id
    if @question.save
      QuestionNotifier.received(@offer, @question).deliver
      redirect_to @offer
    else
      flash[:error] = "Error ocurred on making a questions"
    end
  end

  def edit

  end

  def update
    if @question.update(question_params) && current_user == @question.user
      redirect_to @offer
    else
      render 'edit'
    end
  end

  def destroy
    if current_user == @question.user
      @question.destroy
      redirect_to @offer
    else
      flash[:info] = "You can't delete this question"
      redirect_to @offer
    end
  end

  private
    def find_offer
      @offer = Offer.find(params[:offer_id])
    end

    def question_params
      params.require(:question).permit(:subject, :content, :post_id, :user_id)
    end

    def find_question
      @question = @offer.questions.find(params[:id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.haml
#answer
  .wrapper
    %p= answer.content
    - if current_user.id == answer.user_id
      = link_to "Delete", offer_question_answer_path(answer.question.offer, answer.question, answer), method: :delete

app/views/answers/_form.html.haml
= simple_form_for([@question.offer, @question, @question.answers.build]) do |f|
  = f.input :content
  = f.submit "Submit",  class: "btn btn-primary"

app/views/answers/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Answer

  %h3= @question.content

  = render 'form'

  = link_to "Cancel", offer_path(@question.offer)

app/views/answers/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Answer

  %h3= @question.content

  = render 'form'

  = link_to "Cancel", offer_path(@question.offer)

app/views/layouts/application.html.haml
!!!
%html
%head
  %title TradeBoard
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  .navbar.navbar-default
    .container
      .navbar-header
        = link_to "TradeBoard", root_path, class: "navbar-brand"
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"} States
          %ul.dropdown-menu{"role" => "menu"}
            - State.all.each do |state|
              %li.a= link_to state.title, offers_path(state: state.title)
        - if user_signed_in?
          %li= link_to "New Offer", new_offer_path, class: "navbar-link"
          %li= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-link"
        - else
          %li= link_to "Log In", new_user_session_path, class: "navbar-link"
          %li= link_to "Sign Up", new_user_registration_path, class: "navbar-link"
      = form_tag search_offers_path, method: :get, class: "navbar-form navbar-right", role: "Search" do
        = text_field_tag :search, params[:search], class: "form-control", placeholder: "Search"
        = submit_tag "Search", name: nil, class: "btn btn-default"
  .container
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "alert alert-info"

  = yield

app/views/offers/_form.html.haml
= simple_form_for @offer do |f|
  = f.collection_select :state_id, State.all, :id, :title, {prompt: "Where are you from?" }, class: "form-control"
  = f.input :title, label: "What are you selling?", input_html: {class: "form-control"}
  = f.input :description, label: "Give the details of your product", input_html: {class: "form-control"}
  = f.input :price, label: "How much will it cost?", input_html: {class: "form-control"}
  = f.input :photo, as: :file
  = f.button :submit, class: "btn btn-primary"

app/views/offers/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Offer

  = render 'form'

  = link_to "Cancel", root_path

app/views/offers/index.html.haml
#offers
  .col-md-6.col-md-offset-3
    - @offers.each do |offer|
      %h2= link_to offer.title, offer
      %p=  time_ago_in_words(offer.created_at)

app/views/offers/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Offer

  = render 'form'

  = link_to "Cancel", root_path

app/views/offers/search.html.haml
.row
  - @offers.each do |offer|
    .col-md-6.col-md-offset-3
      %h2= link_to offer.title, offer

app/views/offers/show.html.haml
.col-md-6.col-md-offset-3
  %h1= @offer.title
  %p=  simple_format(@offer.description)
  %h3= number_to_currency(@offer.price, locale: :en)
  %p= image_tag @offer.photo(:medium) unless @offer.photo.blank?
  %p
    Posted by
    = @offer.user.email

  - if user_signed_in?
    %h2 Questions
    = render @offer.questions
    - unless current_user == @offer.user
      %h3 Make a Question
      = render 'questions/form'

    = link_to "Back", root_path
    - if @offer.user == current_user
      = link_to "Edit", edit_offer_path(@offer)
      = link_to "Destroy", offer_path(@offer), method: :delete, data: {confirm: "Are you Sure?"}

app/views/question_notifier/received.html.erb
<h3>Dear @offer.user.email</h3>

<p>
  A user make a question about your offer! The @offer.title
</p>

<p>
  Please go check it out!
</p>

app/views/question_notifier/received.text.erb
QuestionNotifier#received

<%= @greeting %>, find me in app/views/question_notifier/received.text.erb

app/views/questions/_form.html.haml
= simple_form_for([@offer, @offer.questions.build]) do |f|
  = f.input :subject
  = f.input :content
  = f.submit "Create",  class: "btn btn-primary"

app/views/questions/_question.html.haml
%h4.strong= question.subject
%p= question.content
- if current_user == question.user
  = link_to "Edit", edit_offer_question_path(question.offer, question)
  = link_to "Delete", offer_question_path(question.offer, question), method: :delete

- if current_user == question.offer.user
  = link_to "Answer", new_offer_question_answer_path(question.offer, question)
  %hr

= render question.answers

app/views/questions/edit.html.haml
%h1 Edit Question

= simple_form_for([@offer, @question]) do |f|
  = f.input :subject
  = f.input :content
  = f.submit

= link_to 'Back', @offer